### ISSUE TITLE
Add URLs of os and kernel source code

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Open-Source-OS#5]

**Comment by 17bcs029** [comment]
hi @tapaswenipathak actually I'm not find out some url of os. these are the os name can you please help me to find out the links.
* Inferno
* atomos
* its 
* cnchi
* chino os
* Escape
* neu os
* DEOS
* zen
* StateOS
* cuteOS

**Comment by tapaswenipathak** [comment]
On Fri, May 17, 2019 at 1:57 AM Keshav Gupta <notifications@github.com> wrote:
>
> hi @tapaswenipathak actually I need help in finding out few url of os. these are the os name can you please help me in find out the links.

Please find inline
>
> Inferno

https://github.com/infernojs/inferno
> atomos

https://github.com/amaneureka/AtomOS
> its

https://github.com/PDP-10/its
> cnchi

https://github.com/Antergos/Cnchi
> chino os

https://github.com/chino-os/chino-os
> Escape

https://github.com/Geodels/eSCAPE
> neu os

https://github.com/VOID001/neu-os/tree/master/kernel
> DEOS

https://github.com/1deos/deosorg
> zen

https://github.com/Zen-OS
> StateOS

https://github.com/stateos/StateOS
> cuteOS

https://github.com/a-darwish/cuteOS
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
